name: workspace
description: 'Work Space'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  #NETWORK
  dio: ^5.9.0
  http: ^1.5.0
  url_launcher: ^6.3.2
  connectivity_plus: ^6.1.5

  #STATEMANAGEMENT
  bloc: ^9.1.0
  meta: ^1.16.0
  fpdart: ^1.1.1
  equatable: ^2.0.7
  collection: ^1.19.1
  flutter_bloc: ^9.1.1

  #DATABASE
  shared_preferences: ^2.5.3

  #UTILS
  intl: ^0.20.2
  logger: ^2.6.0
  upgrader: ^11.5.0
  share_plus: ^11.1.0
  image_cropper: ^9.1.0
  path_provider: ^2.1.5
  easy_localization: ^3.0.8
  permission_handler: ^12.0.1
  flutter_image_compress: ^2.4.0
  image_gallery_saver_plus: ^4.0.1

  #WIDGETS
  flutter_svg: ^2.2.0
  intl_phone_field: ^3.2.0
  custom_rating_bar: ^3.0.0
  another_flushbar: ^1.12.31
  cached_network_image: ^3.4.1
  infinite_scroll_pagination: ^5.1.1
  syncfusion_flutter_datepicker: ^31.1.22

  #UI&DESIGN
  pinput: ^5.0.2
  shimmer: ^3.0.0
  fl_chart: ^1.1.1
  dotted_line: ^3.2.3
  action_slider: ^0.7.0
  dotted_border: ^3.1.0
  cupertino_icons: ^1.0.8

  #PICKER
  image_picker: ^1.2.0

  #ANIMATION
  animations: ^2.1.1

  #WEBVIEW
  webview_flutter: ^4.13.0
  flutter_widget_from_html: ^0.17.1

  #LOCATION
  location: ^8.0.1
  geocoding: ^4.0.0
  geolocator: ^14.0.1
  flutter_timezone: ^4.1.1
  flutter_osm_plugin: ^1.4.3
  google_maps_flutter: ^2.13.1

  #PAYMENT
  flutter_stripe: ^12.0.2

  #FIREBASE
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  google_sign_in: ^7.2.0
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2
  firebase_messaging: ^16.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  change_app_package_name: ^1.4.0

flutter_launcher_icons:
  ios: true
  min_sdk_android: 24
  remove_alpha_ios: true
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/image/
    - assets/language/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/font/Manrope-ExtraLight.ttf
          weight: 300
        - asset: assets/font/Manrope-Light.ttf
          weight: 400
        - asset: assets/font/Manrope-Regular.ttf
          weight: 500
        - asset: assets/font/Manrope-Medium.ttf
          weight: 600
        - asset: assets/font/Manrope-SemiBold.ttf
          weight: 700
        - asset: assets/font/Manrope-Bold.ttf
          weight: 800
        - asset: assets/font/Manrope-ExtraBold.ttf
          weight: 900
